name: pos701
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1  # Test için bırakıldı - platform dosyalarından farklı versiyon alınacak

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.1
  dio: ^5.4.2+1
  logger: ^2.0.2+1
  fl_chart: ^1.0.0
  shared_preferences: ^2.0.15
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.3.0
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  flutter_svg: ^2.0.10+1
  new_version_plus: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/splash/
    - assets/splash/powered_by.png
